version: '3'
services:
  scala:
    build: .
    stdin_open: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
  postgres:
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: "postgres:latest"
    ports:
     - "5432:5432"
